[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[redirects]]
  from = "/*"
  to = "https://www.mozilla.cz/podpora/"
  status = 301
  force = true


